/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaidAdsRouteImport } from './routes/paid-ads'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SocialMediaRouteImport } from './routes/social-media'
import { Route as WebDesignRouteImport } from './routes/web-design'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidAdsRoute = PaidAdsRouteImport.update({
  id: '/paid-ads',
  path: '/paid-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaRoute = SocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDesignRoute = WebDesignRouteImport.update({
  id: '/web-design',
  path: '/web-design',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/paid-ads': typeof PaidAdsRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/social-media': typeof SocialMediaRoute
  '/web-design': typeof WebDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/paid-ads': typeof PaidAdsRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/social-media': typeof SocialMediaRoute
  '/web-design': typeof WebDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/paid-ads': typeof PaidAdsRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/social-media': typeof SocialMediaRoute
  '/web-design': typeof WebDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/paid-ads' | '/seo' | '/settings' | '/social-media' | '/web-design'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/paid-ads' | '/seo' | '/settings' | '/social-media' | '/web-design'
  id:
    | '__root__'
    | '/'
    | '/paid-ads'
    | '/seo'
    | '/settings'
    | '/social-media'
    | '/web-design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaidAdsRoute: typeof PaidAdsRoute
  SeoRoute: typeof SeoRoute
  SettingsRoute: typeof SettingsRoute
  SocialMediaRoute: typeof SocialMediaRoute
  WebDesignRoute: typeof WebDesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid-ads': {
      id: '/paid-ads'
      path: '/paid-ads'
      fullPath: '/paid-ads'
      preLoaderRoute: typeof PaidAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media': {
      id: '/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof SocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-design': {
      id: '/web-design'
      path: '/web-design'
      fullPath: '/web-design'
      preLoaderRoute: typeof WebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaidAdsRoute: PaidAdsRoute,
  SeoRoute: SeoRoute,
  SettingsRoute: SettingsRoute,
  SocialMediaRoute: SocialMediaRoute,
  WebDesignRoute: WebDesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
